### ISSUE TITLE
Update example from v2 to v2.0, change sleeping time and handle CANCELED status

### ISSUE THREAD

**Issue by igorbelikov** [duckbytes/amplify-build-status#3]
@duckbytes Hi, in your example in readme should be uses: duckbytes/amplify-build-status@**v2.0**, not uses: duckbytes/amplify-build-status@**v2**.

And is it possible to make timeout for sleeping changeable?
I mean >> sleep 30

Also you are not handling the build cancellation status on AWS, this is extremely important as the task is currently stuck waiting indefinitely.:
<img width="384" alt="image" src="https://github.com/duckbytes/amplify-build-status/assets/6455277/0a70621c-37c9-4b13-9418-c5e1db5cb642">

Try to rerun canceled job:
<img width="409" alt="image" src="https://github.com/duckbytes/amplify-build-status/assets/6455277/18a356cc-ffb6-4f57-abf3-7d98102d2287">

**Comment by duckbytes** [comment]
Hey @igorbelikov thanks for the report. Yes I noticed this problem too after making the release. It happens when a single commit has multiple builds.

I'm not sure if it was a bug I introduced with v2. You could try v1.1 if you're stuck, but that one is missing some extra features like getting the env name and graphql endpoint. Alternatively you could push up a new commit and it should work on v2.

I might be able look for a fix this weekend.

**Comment by igorbelikov** [comment]
thanks, I'll try to test again, in simple use action works fine.

**Comment by duckbytes** [comment]
Should be fixed now in v2.1. Let me know if you have any more issues.

**Comment by igorbelikov** [comment]
@duckbytes thanks, action works fine! 

About "sleep 30", can you replace sleep timeout to params please? This would be great, since now deployment time is wasted :)
